---
## Reload system daemons or services
- name: Restart services for Debian systems
  become: yes
  become_method: sudo
  become_user: root
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - uwsgi
    - nginx
    - postgresql
